# Generated by Django 3.0.4 on 2020-03-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videofile',
            field=models.FileField(default=None, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
